// Date: 16-11-2013 11:11:55
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.juicegrape.juicewares.client.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelCabinet extends ModelBase
{
  //fields
    ModelRenderer Bottom;
    ModelRenderer Back;
    ModelRenderer Right_Side;
    ModelRenderer Left_Side;
    ModelRenderer Top;
    ModelRenderer Shelve;
  
  public ModelCabinet()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      Bottom = new ModelRenderer(this, 0, 0);
      Bottom.addBox(-7F, 0F, -7F, 14, 1, 14);
      Bottom.setRotationPoint(0F, 23F, 0F);
      Bottom.setTextureSize(128, 64);
//      Bottom.mirror = true;
//      setRotation(Bottom, 0F, 0F, 0F);
      Back = new ModelRenderer(this, 0, 15);
      Back.addBox(-7F, -6F, 0F, 14, 12, 1);
      Back.setRotationPoint(0F, 17F, 6F);
      Back.setTextureSize(128, 64);
//      Back.mirror = true;
//      setRotation(Back, 0F, 0F, 0F);
      Right_Side = new ModelRenderer(this, 30, 15);
      Right_Side.addBox(0F, -6F, -6.5F, 1, 12, 13);
      Right_Side.setRotationPoint(-7F, 17F, -0.5F);
      Right_Side.setTextureSize(128, 64);
//      Right_Side.mirror = true;
//      setRotation(Right_Side, 0F, 0F, 0F);
      Left_Side = new ModelRenderer(this, 30, 15);
      Left_Side.addBox(0F, -6F, -6.5F, 1, 12, 13);
      Left_Side.setRotationPoint(6F, 17F, -0.5F);
      Left_Side.setTextureSize(128, 64);
//      Left_Side.mirror = true;
 //     setRotation(Left_Side, 0F, 0F, 0F);
      Top = new ModelRenderer(this, 0, 0);
      Top.addBox(-7F, 0F, -7F, 14, 1, 14);
      Top.setRotationPoint(0F, 10F, 0F);
      Top.setTextureSize(128, 64);
//      Top.mirror = true;
//      setRotation(Top, 0F, 0F, 0F);
      Shelve = new ModelRenderer(this, 0, 40);
      Shelve.addBox(-6F, 0F, -6F, 12, 1, 12);
      Shelve.setRotationPoint(0F, 17F, 0F);
      Shelve.setTextureSize(128, 64);
//      Shelve.mirror = true;
//      setRotation(Shelve, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Bottom.render(f5);
    Back.render(f5);
    Right_Side.render(f5);
    Left_Side.render(f5);
    Top.render(f5);
    Shelve.render(f5);
  }
  
  @SuppressWarnings("unused")
private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f1, float f2, float f3, float f4, float f5, float f6, Entity entity)
  {
    super.setRotationAngles(f1, f2, f3, f4, f5, f6, entity);


  }

}
